// frontend/src/components/CalibrationSettings.tsx
import { useEffect } from 'react';

export interface LikelihoodModel {
	mu_delay: number;
	stddev_delay: number;
	outliers: number;
	period: number;
}

interface CalibrationSettingsProps {
	useAutomaticCalibration: boolean;
	setUseAutomaticCalibration: (value: boolean) => void;
	likelihoodModel: LikelihoodModel;
	setLikelihoodModel: (updater: (prev: LikelihoodModel) => LikelihoodModel) => void;
	autoCalibrationLikelihoodModel: LikelihoodModel;
}

function CalibrationSettings({
	useAutomaticCalibration,
	setUseAutomaticCalibration,
	likelihoodModel,
	setLikelihoodModel,
	autoCalibrationLikelihoodModel,
}: CalibrationSettingsProps) {
	// Sync model from auto-calibration whenever it is enabled or updates
	useEffect(() => {
		if (useAutomaticCalibration) {
			setLikelihoodModel(() => ({ ...autoCalibrationLikelihoodModel }));
		}
	}, [useAutomaticCalibration, autoCalibrationLikelihoodModel, setLikelihoodModel]);

	const handleSlider =
		(field: keyof LikelihoodModel) =>
		(e: React.ChangeEvent<HTMLInputElement>) => {
			setLikelihoodModel((prev) => ({ ...prev, [field]: parseFloat(e.target.value) }));
			setUseAutomaticCalibration(false);
		};

	return (
		<div className="flex flex-col gap-3 rounded-lg border border-white/10 bg-white/5 p-3 text-white">
			<div className="flex items-center gap-2">
				<label className="text-sm font-semibold text-gray-100">Auto Calibration</label>
				<input
					type="checkbox"
					checked={useAutomaticCalibration}
					onChange={(e) => setUseAutomaticCalibration(e.target.checked)}
					className="h-4 w-4 accent-blue-500"
				/>
			</div>

			<div className="grid grid-cols-2 gap-2">
				<SliderRow
					label={`Mean (${(1000 * likelihoodModel.mu_delay).toFixed(0)}ms)`}
					min={-0.05}
					max={0.2}
					step={0.001}
					value={likelihoodModel.mu_delay}
					onChange={handleSlider('mu_delay')}
				/>
				<SliderRow
					label={`StdDev (${(1000 * likelihoodModel.stddev_delay).toFixed(0)}ms)`}
					min={0}
					max={0.15}
					step={0.001}
					value={likelihoodModel.stddev_delay}
					onChange={handleSlider('stddev_delay')}
				/>
				<SliderRow
					label={`Outliers (${(100 * likelihoodModel.outliers).toFixed(1)}%)`}
					min={0}
					max={0.25}
					step={0.001}
					value={likelihoodModel.outliers}
					onChange={handleSlider('outliers')}
				/>
				<SliderRow
					label={`Period (${likelihoodModel.period.toFixed(2)}s)`}
					min={0.3}
					max={2.5}
					step={0.01}
					value={likelihoodModel.period}
					onChange={handleSlider('period')}
				/>
			</div>
		</div>
	);
}

interface SliderRowProps {
	label: string;
	min: number;
	max: number;
	step: number;
	value: number;
	onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
}

function SliderRow({ label, min, max, step, value, onChange }: SliderRowProps) {
	return (
		<div className="flex flex-col gap-1 rounded-md border border-white/8 bg-black/20 p-2">
			<label className="text-sm font-medium text-gray-200">{label}</label>
			<input
				type="range"
				min={min}
				max={max}
				step={step}
				value={value}
				onChange={onChange}
				className="w-full accent-blue-500"
			/>
		</div>
	);
}

export default CalibrationSettings;

// src/routes/v2/CalibrationSettings.svelte
<script>
    // import Cookies from 'js-cookie';
    export let use_automatic_calibration;
    export let likelihood_model;
    export let auto_calibration_likelihood_model;
    $: if (use_automatic_calibration) {
        console.log("use_automatic_calibration", use_automatic_calibration);
        likelihood_model.mu_delay = auto_calibration_likelihood_model.mu_delay;
        likelihood_model.stddev_delay = auto_calibration_likelihood_model.stddev_delay;
        likelihood_model.outliers = auto_calibration_likelihood_model.outliers;
        likelihood_model.period = auto_calibration_likelihood_model.period;
    }
    function save_likelihood_model() {
        use_automatic_calibration = false;
        // Cookies.set('likelihood_model', JSON.stringify(likelihood_model));
    }
</script>
<div class="flex flex-col border border-gray-300 rounded-md bg-white p-1.5 gap-1.5">
    <div class="flex items-center gap-1.5">
        <label class="font-bold text-s">Auto Calibration</label>
        <input type="checkbox" bind:checked={use_automatic_calibration} />
    </div>

    <div class="grid grid-cols-2 gap-2">
        <div class="flex flex-col gap-0.5">
            <label class="font-bold text-s">Mean ({(1000 * likelihood_model.mu_delay).toFixed(0)}ms)</label>
            <input type="range" min="-0.050" max="0.200" step="0.001" bind:value={likelihood_model.mu_delay} on:input={save_likelihood_model} class="w-full"/>
        </div>

        <div class="flex flex-col gap-0.5">
            <label class="font-bold text-s">StdDev ({(1000 * likelihood_model.stddev_delay).toFixed(0)}ms)</label>
            <input type="range" min="0" max="0.150" step="0.001" bind:value={likelihood_model.stddev_delay} on:input={save_likelihood_model} class="w-full"/>
        </div>

        <div class="flex flex-col gap-0.5">
            <label class="font-bold text-s">Outliers ({(100 * likelihood_model.outliers).toFixed(1)}%)</label>
            <input type="range" min="0" max="0.250" step="0.001" bind:value={likelihood_model.outliers} on:input={save_likelihood_model} class="w-full"/>
        </div>

        <div class="flex flex-col gap-0.5">
            <label class="font-bold text-s">Period ({likelihood_model.period.toFixed(2)}s)</label>
            <input type="range" min="0.3" max="2.5" step="0.01" bind:value={likelihood_model.period} on:input={save_likelihood_model} class="w-full"/>
        </div>
    </div>
</div>
