// frontend/src/components/TrieVisualizer.tsx
import { useEffect, useRef, useState, useCallback } from 'react';
import { colorFromLetter } from '../utils/colors';
import { logaddexp } from '../utils/trie_logic';
import type { TrieNode } from '../utils/trie_logic';
import type { LikelihoodModel } from './CalibrationSettings';
import type { DelayPair } from '../utils/stats';
import Eye from './Eye';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const TWEEN_DURATION_MS = 300;
const BOX_WIDTH = 37;
const BOX_WIDTH_CHILDREN_MULTIPLIER = 1.0;
const TIMER_CIRCLE_RADIUS = 15;
const TIMER_CIRCLE_WIDTH = 2;
const TIMER_FONT_SIZE = 37;

// ---------------------------------------------------------------------------
// Prop types
// ---------------------------------------------------------------------------

export interface SetLikelihoodsEvent {
	new_likelihoods: Record<string, { likelihood: number; delay_pair: DelayPair }>;
	click_seq: number[];
}

interface TrieVisualizerProps {
	trie: TrieNode;
	trieUpdatedFlag: boolean;
	setTrieUpdatedFlag: (value: boolean) => void;
	useVisualTutor: boolean;
	setUseVisualTutor: (value: boolean) => void;
	targetPhrase: string;
	onSetLikelihoods: (event: SetLikelihoodsEvent) => void;
	likelihoodModel: LikelihoodModel;
	multilineMode: boolean;
	setMultilineMode: (value: boolean) => void;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function interpolate(start: number, end: number, progress: number): number {
	return start + (end - start) * progress;
}

function normalLogpdf(x: number, mean: number, stddev: number): number {
	return (
		-0.5 * Math.pow((x - mean) / stddev, 2) - Math.log(stddev * Math.sqrt(2 * Math.PI))
	);
}

function timerLikelihood(
	time: number,
	phase: number,
	model: LikelihoodModel,
): { likelihood: number; delay_pair: DelayPair } {
	let delay = time - phase;
	delay = ((delay + model.period * 1.5) % model.period) - model.period / 2;
	
	let x = time - phase;
	x = ((x % model.period) + model.period) % model.period;
	const outlierProb = Math.log(model.outliers) - Math.log(model.period);
	const notOutlierProb = Math.log(1 - model.outliers);
	
	const normalModes = [-1, 0, 1].map(k => {
		return normalLogpdf(x, model.mu_delay + k * model.period, model.stddev_delay);
	});
	
	let sumNormalModes = normalModes[0];
	for (let i = 1; i < normalModes.length; i++) {
		sumNormalModes = logaddexp(sumNormalModes, normalModes[i]);
	}

	return {
		likelihood: logaddexp(
			outlierProb,
			notOutlierProb + sumNormalModes
		),
		delay_pair: { delay, period: model.period },
	};
}

function playClickSound(): void {
	const ctx = new AudioContext();
	const osc = ctx.createOscillator();
	const gain = ctx.createGain();
	osc.frequency.value = 1000;
	gain.gain.setValueAtTime(1, ctx.currentTime);
	gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.05);
	osc.connect(gain);
	gain.connect(ctx.destination);
	osc.start(ctx.currentTime);
	osc.stop(ctx.currentTime + 0.05);
}

// ---------------------------------------------------------------------------
// Tween bookkeeping (module-level to avoid re-creation)
// ---------------------------------------------------------------------------

type TweenKey = string;
interface TweenEntry {
	start: number;
	from: number;
	to: number;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

function TrieVisualizer({
	trie,
	trieUpdatedFlag,
	setTrieUpdatedFlag,
	useVisualTutor,
	setUseVisualTutor,
	targetPhrase,
	onSetLikelihoods,
	likelihoodModel,
	multilineMode,
	setMultilineMode,
}: TrieVisualizerProps) {
	const canvasRef = useRef<HTMLCanvasElement>(null);
	const [ctx, setCtx] = useState<CanvasRenderingContext2D | null>(null);
	const [firstBoxHeight, setFirstBoxHeight] = useState(0);
	const [visibleNodes, setVisibleNodes] = useState<TrieNode[]>([]);
	const [devicePixelRatio, setDevicePixelRatio] = useState(1);
	const [showBoxes, setShowBoxes] = useState(true);
	const [blinkToClick, setBlinkToClick] = useState(true);
	const [playClickSoundEnabled, setPlayClickSoundEnabled] = useState(false);
	const [developerVisualizer, setDeveloperVisualizer] = useState(false);
	const [leftOffset] = useState(0);
	const [clickSeq, setClickSeq] = useState<number[]>([]);

	const animationFrameRef = useRef<number | null>(null);
	const tweenStartTimesRef = useRef<Record<TweenKey, TweenEntry>>({});
	const oldVisibleRegistryRef = useRef<Record<string, TrieNode>>({});
	const keepPhasesRef = useRef(false);

	// ------------------------------------------------------------------
	// Tween helpers
	// ------------------------------------------------------------------

	const getTweenedValue = useCallback(
		(node: TrieNode, property: string, currentTime: number): number => {
			const key: TweenKey = `${node.val}_${property}`;
			const raw = (node as unknown as Record<string, number>)[property] ?? 0;
			if (!tweenStartTimesRef.current[key]) {
				tweenStartTimesRef.current[key] = { start: currentTime, from: raw, to: raw };
			}
			const tween = tweenStartTimesRef.current[key];
			const progress = Math.min((currentTime - tween.start) / (TWEEN_DURATION_MS / 1000), 1);
			return interpolate(tween.from, tween.to, progress);
		},
		[],
	);

	const updateTween = useCallback(
		(node: TrieNode, property: string, targetValue: number, currentTime: number): void => {
			const key: TweenKey = `${node.val}_${property}`;
			if (!tweenStartTimesRef.current[key]) {
				tweenStartTimesRef.current[key] = { start: currentTime, from: targetValue, to: targetValue };
				return;
			}
			const current = getTweenedValue(node, property, currentTime);
			tweenStartTimesRef.current[key] = { start: currentTime, from: current, to: targetValue };
		},
		[getTweenedValue],
	);

	// ------------------------------------------------------------------
	// Layout (setLocations)
	// ------------------------------------------------------------------

	const setLocations = useCallback(
		(
			node: TrieNode,
			rootCall = false,
			loc = { x: 0, y: 0 },
			sizeHeight = firstBoxHeight,
			sizeWidth = BOX_WIDTH,
			accumulatedNodes: TrieNode[] | null = null,
		): void => {
			const oldVisibleRegistry = oldVisibleRegistryRef.current;
			const keepPhases = keepPhasesRef.current;
			const nodesList: TrieNode[] = rootCall ? [] : (accumulatedNodes ?? []);

			if (rootCall) {
				loc = { x: 0, y: 0 };
				sizeWidth *= 1.5;
			}

			const currentTime = performance.now() / 1000;
			nodesList.push(node);

			node.location = { ...loc };
			node.size_height = sizeHeight;
			node.size_width = sizeWidth;

			updateTween(node, 'location_x', loc.x, currentTime);
			updateTween(node, 'location_y', loc.y, currentTime);
			updateTween(node, 'size_height', sizeHeight, currentTime);
			updateTween(node, 'size_width', sizeWidth, currentTime);

			if (node.val in oldVisibleRegistry && keepPhases) {
				node.phase = oldVisibleRegistry[node.val].phase;
			} else {
				node.phase = Math.random() * likelihoodModel.period;
			}

			const visibleChildren = node.children.filter(
				(c) => c.is_visible || (keepPhases && c.val in oldVisibleRegistry),
			);
			const visibleChildrenVals = new Set(visibleChildren.map((c) => c.val));

			if (visibleChildren.length > 0) {
				const numChildren = visibleChildren.length;
				const boxWidthMultiplier = 1 + BOX_WIDTH_CHILDREN_MULTIPLIER * Math.log(numChildren);
				let yRelativeBottom = 0;
				const totalChildrenPostZ = node.children.reduce(
					(acc, c) => logaddexp(acc, c.post_Z),
					-Infinity,
				);

				node.children.forEach((child) => {
					const childFrac = child.post_Z - totalChildrenPostZ;
					const childHeight = sizeHeight * Math.exp(childFrac);

					if (visibleChildrenVals.has(child.val)) {
						if (!(child.val in oldVisibleRegistry)) {
							const now = performance.now() / 1000;
							if (node.val === '' || !keepPhases) {
								child.go_live_time = now;
							} else if (node.go_live_time !== undefined && now < node.go_live_time) {
								child.go_live_time = node.go_live_time;
							} else {
								const phase = node.phase ?? 0;
								let timeRemaining = (phase - now) % likelihoodModel.period;
								timeRemaining = ((timeRemaining % likelihoodModel.period) + likelihoodModel.period) % likelihoodModel.period;
								const timeSinceLast = likelihoodModel.period - timeRemaining;
								const parentGoLive = node.go_live_time ?? 0;
								if (timeSinceLast < 0.25 || now < parentGoLive + 0.25) {
									child.go_live_time = now;
								} else {
									child.go_live_time =
										now + timeRemaining + likelihoodModel.mu_delay + 2.5 * likelihoodModel.stddev_delay;
								}
							}
						}
						setLocations(
							child,
							false,
							{ x: node.location!.x + node.size_width!, y: node.location!.y + yRelativeBottom },
							childHeight,
							boxWidthMultiplier * BOX_WIDTH,
							nodesList,
						);
					}
					yRelativeBottom += childHeight;
				});
			}

			if (rootCall) {
				const newRegistry: Record<string, TrieNode> = {};
				nodesList.forEach((n) => { newRegistry[n.val] = n; });
				oldVisibleRegistryRef.current = newRegistry;
				if (!keepPhases) keepPhasesRef.current = true;
				setVisibleNodes([...nodesList]);
			}
		},
		[firstBoxHeight, likelihoodModel, updateTween],
	);

	// ------------------------------------------------------------------
	// Click handler
	// ------------------------------------------------------------------

	const click = useCallback(
		(event: MouseEvent | KeyboardEvent | { timeStamp: number }) => {
			if (playClickSoundEnabled) playClickSound();

			const time =
				'timeStamp' in event && event.timeStamp
					? event.timeStamp / 1000
					: performance.now() / 1000;

			const newClickSeq = [...clickSeq, time];
			setClickSeq(newClickSeq);

			const now = performance.now() / 1000;
			const newLikelihoods: Record<string, { likelihood: number; delay_pair: DelayPair }> = {};
			visibleNodes
				.filter((node) => !(node.go_live_time && node.go_live_time > now))
				.forEach((node) => {
					newLikelihoods[node.val] = timerLikelihood(time, node.phase ?? 0, likelihoodModel);
				});

			keepPhasesRef.current = false;
			onSetLikelihoods({ new_likelihoods: newLikelihoods, click_seq: newClickSeq });
		},
		[clickSeq, visibleNodes, likelihoodModel, playClickSoundEnabled, onSetLikelihoods],
	);

	const handleBlink = useCallback(() => {
		click({ timeStamp: performance.now() });
	}, [click]);

	// ------------------------------------------------------------------
	// Canvas setup and event listeners
	// ------------------------------------------------------------------

	useEffect(() => {
		if (!canvasRef.current) return;
		const canvas = canvasRef.current;
		const context = canvas.getContext('2d');
		if (!context) return;

		setCtx(context);
		setFirstBoxHeight(canvas.clientHeight);

		const dpr = window.devicePixelRatio || 1;
		setDevicePixelRatio(dpr);
		const rect = canvas.getBoundingClientRect();
		canvas.width = rect.width * dpr;
		canvas.height = rect.height * dpr;
		context.setTransform(dpr, 0, 0, dpr, 0, 0);
		canvas.style.width = `${rect.width}px`;
		canvas.style.height = `${rect.height}px`;
		canvas.tabIndex = 0;
	}, []);

	// Attach event listeners whenever `click` changes
	useEffect(() => {
		if (!canvasRef.current) return;
		const canvas = canvasRef.current;

		const handleKeyDown = (e: KeyboardEvent) => {
			if (e.code === 'Space') {
				const tag = (document.activeElement as HTMLElement).tagName;
				const isText =
					(tag === 'INPUT' || tag === 'TEXTAREA') &&
					(document.activeElement as HTMLInputElement).type !== 'checkbox';
				if (!isText) {
					click(e);
					e.preventDefault();
				}
			}
		};

		document.addEventListener('keydown', handleKeyDown);
		canvas.addEventListener('click', click as EventListener);

		return () => {
			document.removeEventListener('keydown', handleKeyDown);
			canvas.removeEventListener('click', click as EventListener);
		};
	}, [click]);

	// Re-layout trie when it changes
	useEffect(() => {
		if (trieUpdatedFlag) {
			setLocations(trie, true);
			setTrieUpdatedFlag(false);
		}
	}, [trieUpdatedFlag, trie, setLocations, setTrieUpdatedFlag]);

	// ------------------------------------------------------------------
	// Draw loop
	// ------------------------------------------------------------------

	const draw = useCallback(() => {
		if (!ctx || !canvasRef.current) return;

		const time = performance.now() / 1000;
		const currentTime = time;
		const now = time;

		ctx.setTransform(1, 0, 0, 1, 0, 0);
		ctx.clearRect(0, 0, canvasRef.current.width, canvasRef.current.height);
		ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0);

		const liveNodes = visibleNodes.filter(
			(n) => !(n.go_live_time && n.go_live_time > now),
		);

		// Find the longest target-prefix on screen (for visual tutor)
		let longestTargetVal = '';
		liveNodes.forEach((node) => {
			if (
				targetPhrase.startsWith(node.val) &&
				node.val.length > longestTargetVal.length
			) {
				longestTargetVal = node.val;
			}
		});

		// Draw that node last (on top)
		liveNodes.sort((a, b) => {
			if (a.val === longestTargetVal) return 1;
			if (b.val === longestTargetVal) return -1;
			return 0;
		});

		// Background boxes
		liveNodes.forEach((node) => {
			if (!showBoxes && !developerVisualizer) return;
			const color = colorFromLetter(node.letter);
			const fill = `rgba(${color[0]}, ${color[1]}, ${color[2]}, 0.13)`;
			const locX = getTweenedValue(node, 'location_x', currentTime);
			const locY = getTweenedValue(node, 'location_y', currentTime);
			const sizeW = getTweenedValue(node, 'size_width', currentTime);
			const sizeH = getTweenedValue(node, 'size_height', currentTime);

			ctx.beginPath();
			ctx.rect(locX - leftOffset + 3, locY + 3, sizeW - 6, sizeH - 6);
			ctx.fillStyle = fill;
			ctx.fill();
			ctx.closePath();
		});

		// Connections
		const registry: Record<string, TrieNode> = {};
		visibleNodes.forEach((n) => { registry[n.val] = n; });

		liveNodes.forEach((node) => {
			if (node.val.length < 1) return;
			const parentNode = registry[node.val.slice(0, -1)];
			if (!parentNode) return;

			const color = colorFromLetter(node.letter);
			const darker = `rgba(${Math.floor(color[0] / 1.8)}, ${Math.floor(color[1] / 1.8)}, ${Math.floor(color[2] / 1.8)}, 1.0)`;

			const nX = getTweenedValue(node, 'location_x', currentTime);
			const nY = getTweenedValue(node, 'location_y', currentTime);
			const nW = getTweenedValue(node, 'size_width', currentTime);
			const nH = getTweenedValue(node, 'size_height', currentTime);
			const pX = getTweenedValue(parentNode, 'location_x', currentTime);
			const pY = getTweenedValue(parentNode, 'location_y', currentTime);
			const pW = getTweenedValue(parentNode, 'size_width', currentTime);
			const pH = getTweenedValue(parentNode, 'size_height', currentTime);

			const startX = nX + nW - leftOffset;
			const startY = nY + nH / 2;
			const endX = pX + pW - leftOffset;
			const endY = pY + pH / 2;
			const midX = (startX + endX) / 2;

			ctx.beginPath();
			ctx.moveTo(startX, startY);
			ctx.bezierCurveTo(midX, startY, midX, endY, endX, endY);
			ctx.strokeStyle = darker;
			ctx.lineWidth = 2;
			ctx.stroke();
			ctx.closePath();
		});

		// Timer circles + letters
		liveNodes.forEach((node) => {
			const timerFrac =
				((time - (node.phase ?? 0) + likelihoodModel.period) % likelihoodModel.period) /
				likelihoodModel.period;
			const color = colorFromLetter(node.letter);
			const colorStr = `rgba(${color[0]}, ${color[1]}, ${color[2]}, 1.0)`;
			const isTarget = useVisualTutor && node.val === longestTargetVal;

			let timerFontSize = TIMER_FONT_SIZE;
			let timerRadius = TIMER_CIRCLE_RADIUS;
			if (isTarget) {
				timerFontSize *= 2;
				timerRadius *= 2;
			}
			if (node.letter === 'm' || node.letter === 'w') timerRadius *= 1.15;

			const locX = getTweenedValue(node, 'location_x', currentTime);
			const locY = getTweenedValue(node, 'location_y', currentTime);
			const sizeW = getTweenedValue(node, 'size_width', currentTime);
			const sizeH = getTweenedValue(node, 'size_height', currentTime);

			const cx = locX + sizeW - leftOffset - TIMER_CIRCLE_RADIUS;
			const cy = locY + sizeH / 2;

			if (isTarget) {
				ctx.beginPath();
				ctx.arc(cx, cy, TIMER_CIRCLE_RADIUS * 3, 0, 2 * Math.PI);
				ctx.fillStyle = 'rgba(255, 255, 255, 0.2)';
				ctx.fill();
				ctx.closePath();
			}

			ctx.beginPath();
			ctx.fillStyle = colorStr;
			if (node.letter === '$') {
				const sq = 17;
				ctx.fillRect(cx - sq / 2, cy - sq / 2, sq, sq);
			} else {
				ctx.font = `${timerFontSize}px verdana, helvetica, sans-serif`;
				ctx.textAlign = 'center';
				ctx.textBaseline = 'middle';
				ctx.fillText(node.letter, cx, cy);
			}

			if (developerVisualizer) {
				ctx.font = `${timerFontSize / 3}px verdana, helvetica, sans-serif`;
				ctx.fillText(`l:${node.likelihood?.toFixed(2) ?? '0'}`, cx, cy + timerFontSize / 3);
				ctx.fillText(`p:${node.prior?.toFixed(2) ?? '0'}`, cx, cy + (2 * timerFontSize) / 3);
				ctx.fillText(`z:${node.post_Z?.toFixed(2) ?? '0'}`, cx, cy + timerFontSize);
			}
			ctx.closePath();

			// Timer arc
			ctx.beginPath();
			ctx.arc(cx, cy, timerRadius, 0, 2 * Math.PI * timerFrac);
			ctx.strokeStyle = `rgba(${color[0]}, ${color[1]}, ${color[2]}, ${timerFrac * 0.9 + 0.1})`;
			ctx.lineWidth = isTarget ? TIMER_CIRCLE_WIDTH * 2 : TIMER_CIRCLE_WIDTH;
			ctx.stroke();
			ctx.closePath();
		});

		animationFrameRef.current = requestAnimationFrame(draw);
	}, [
		ctx,
		visibleNodes,
		devicePixelRatio,
		leftOffset,
		targetPhrase,
		useVisualTutor,
		developerVisualizer,
		showBoxes,
		likelihoodModel,
		getTweenedValue,
	]);

	useEffect(() => {
		if (ctx) draw();
		return () => {
			if (animationFrameRef.current !== null) {
				cancelAnimationFrame(animationFrameRef.current);
			}
		};
	}, [draw, ctx]);

	// ------------------------------------------------------------------
	// Render
	// ------------------------------------------------------------------

	return (
		<div className="flex flex-col h-full relative box-border">
			<canvas ref={canvasRef} className="h-full w-full bg-black" />

			<div className="absolute top-4 right-6 flex gap-8 text-white text-2xl">
				<CheckboxLabel
					label="Blink to click"
					checked={blinkToClick}
					onChange={setBlinkToClick}
				/>
				<CheckboxLabel
					label="Debug"
					checked={developerVisualizer}
					onChange={setDeveloperVisualizer}
				/>
				<CheckboxLabel
					label="Click sound"
					checked={playClickSoundEnabled}
					onChange={setPlayClickSoundEnabled}
				/>
				<CheckboxLabel
					label="Boxes"
					checked={showBoxes}
					onChange={setShowBoxes}
				/>
				<CheckboxLabel
					label="Tutor"
					checked={useVisualTutor}
					onChange={setUseVisualTutor}
				/>
				<CheckboxLabel
					label="Multiline"
					checked={multilineMode}
					onChange={setMultilineMode}
				/>
			</div>

			{blinkToClick && <Eye onBlink={handleBlink} />}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Small helper component
// ---------------------------------------------------------------------------

interface CheckboxLabelProps {
	label: string;
	checked: boolean;
	onChange: (value: boolean) => void;
}

function CheckboxLabel({ label, checked, onChange }: CheckboxLabelProps) {
	return (
		<label className="flex items-center gap-3">
			<input
				type="checkbox"
				checked={checked}
				onChange={(e) => onChange(e.target.checked)}
				className="w-6 h-6"
			/>
			{label}
		</label>
	);
}

export default TrieVisualizer;

// src/routes/v2/TrieVisualizer.svelte
<script>
    import { onMount } from 'svelte';
    import { get, writable } from 'svelte/store';
    import { tweened } from 'svelte/motion';
    import { linear } from 'svelte/easing';
    import { createEventDispatcher } from 'svelte';
    import Eye from './Eye.svelte';
    const dispatch = createEventDispatcher();
    import * as colors from '$lib/colors.js';
    let canvas_element;
    let fps = 0;
    let lastFrameTime = 0;
    let pause_timer = false;
    let wpm_timer_start = 0;
    let time_elapsed = 0;
    let left_offset = writable(0);
    let ctx;
    let animationFrameId;
    let FIRST_BOX_HEIGHT;
    let BOX_WIDTH = 37;
    let BOX_WIDTH_CHILDREN_MULTIPLIER = 1.0;
    let TIMER_CIRCLE_RADIUS = 15;
    let TIMER_CIRCLE_WIDTH = 2;
    let TIMER_FONT_SIZE = 37;
    let TIMER_COLOR = 'color';
    let visible_nodes = [];
    let click_seq = [];
    let old_visible_registry = {};
    let keep_phases = false;
    let developer_visualizer = false;
    let show_boxes = true;
    let blink_to_click = true;
    let play_click_sound = false;
    const TWEEN_DURATION = 300;
    const TWEEN_EASING = linear;
    let FPS_SMOOTHING = 0.9;
    export let likelihood_model;
    export let trie;
    export let trie_updated_flag;
    export let use_visual_tutor;
    export let target_phrase;
    export let multiline_mode = false;
    trie_updated_flag.subscribe(new_trie_updated_flag => {
        if (new_trie_updated_flag) {
            setLocations(trie, true);
            trie_updated_flag.set(false);
        }
    });

    function playClickSound() {
        const audioContext = new (window.AudioContext || window.webkitAudioContext)();

        // Create an oscillator
        const oscillator = audioContext.createOscillator();
        const gainNode = audioContext.createGain();

        // Set the oscillator frequency for a "click" sound
        oscillator.frequency.value = 1000; // Frequency in Hz (adjust as needed)

        // Set the gain envelope to make it very short (click-like)
        gainNode.gain.setValueAtTime(1, audioContext.currentTime); // Start at full volume
        gainNode.gain.exponentialRampToValueAtTime(0.001, audioContext.currentTime + 0.05); // Fade quickly

        // Connect oscillator to the gain, and then to the audio context
        oscillator.connect(gainNode);
        gainNode.connect(audioContext.destination);

        // Start and stop the oscillator quickly
        oscillator.start(audioContext.currentTime);
        oscillator.stop(audioContext.currentTime + 0.05); // 50ms for a short click
    }

    onMount(async () => {
        ctx = canvas_element.getContext('2d');
        FIRST_BOX_HEIGHT = canvas_element.clientHeight;
        
        // Get the device pixel ratio
        const dpr = window.devicePixelRatio || 1;
        // Set the canvas size accounting for device pixel ratio
        const rect = canvas_element.getBoundingClientRect();
        canvas_element.width = rect.width * dpr;
        canvas_element.height = rect.height * dpr;
        // Scale the canvas context
        ctx.scale(dpr, dpr);
        // Set the CSS size
        canvas_element.style.width = `${rect.width}px`;
        canvas_element.style.height = `${rect.height}px`;
        // start animation loop
        canvas_element.tabIndex = 0; // Make canvas focusable
        document.addEventListener('keydown', (event) => {
            if (event.code === 'Space') {
                const activeTag = document.activeElement.tagName;
                const isTextInput = (activeTag === 'INPUT' || activeTag === 'TEXTAREA') && document.activeElement.type !== 'checkbox';
                if (!isTextInput) {
                    click(event);
                    event.preventDefault();
                }
            }
        });
        //
        draw();
    });

    let get_timer_frac = (node, time) => {
        return (time - node.phase + likelihood_model.period) % likelihood_model.period / likelihood_model.period;
    }

    function normal_pdf(x, mean, stddev) {
        return Math.exp(-0.5 * Math.pow((x - mean) / stddev, 2)) / (stddev * Math.sqrt(2 * Math.PI));
    }
    function normal_logpdf(x, mean, stddev) {
        return -0.5 * Math.pow((x - mean) / stddev, 2) - Math.log(stddev * Math.sqrt(2 * Math.PI));
    }

    function logaddexp(a, b) {
        if (a === -Infinity) {
            return b;
        }
        if (b === -Infinity) {
            return a;
        }
        if (a > b) {
            return a + Math.log(1 + Math.exp(b - a));
        } else {
            return b + Math.log(1 + Math.exp(a - b));
        }
    }

    function timer_likelihood(time, phase, likelihood_model) {
        // likelihood model has the fields:
        // - mu_delay
        // - stddev_delay
        // - outliers
        // - period
        let delay = time - phase
        // map to [-period/2, period/2]
        delay = ((delay + likelihood_model.period*1.5) % likelihood_model.period) - likelihood_model.period/2.0;
	let dist = Math.abs(delay - likelihood_model.mu_delay);
	// wrap around to find the closet distance
	// N.B. at high frequencies it becomes especially clear how much easier it is to select a timer when there are not competing timers nearby
    // Color also more obviously matters e.g. red timers are harder than white timers
	dist = Math.min(dist, likelihood_model.period - dist); // Added 12/2/25
        const gaussian_log_likelihood = normal_logpdf(delay, likelihood_model.mu_delay, likelihood_model.stddev_delay);
        const uniform_log_likelihood = Math.log( 1 / likelihood_model.period);
        const outlier_prob = Math.log(likelihood_model.outliers);
        const not_outlier_prob = Math.log(1 - likelihood_model.outliers);
        return {
            likelihood: logaddexp(not_outlier_prob + gaussian_log_likelihood, outlier_prob + uniform_log_likelihood),
            // TODO: use a tuple since we don't like dragging this about
            delay_pair: {
                delay,
                period: likelihood_model.period,
            }
        }
    }

    function click(event) {
        if (play_click_sound) {
            playClickSound();
        }
        let time;
        if (event && event.timeStamp) {
            time = event.timeStamp / 1000.0;
        } else {
            time = performance.now() / 1000.0;
        }
        click_seq.push(time);
        let new_likelihoods = {};
        visible_nodes.filter(node => !(node.go_live_time && node.go_live_time > time)).forEach(node => {
            let node_timer_likelihood = timer_likelihood(time, node.phase, likelihood_model);
            new_likelihoods[node.val] = node_timer_likelihood;
        });
        keep_phases = false;
        let payload = {new_likelihoods, click_seq};
        dispatch('set_likelihoods', payload);
    }

    function setLocations(node, root_call = false,  loc = null, size_height = FIRST_BOX_HEIGHT, size_width = BOX_WIDTH) {
        if (root_call) {
            loc = { x: 0, y: 0 };
            size_width *= 1.5;
            visible_nodes = [];
        }
        visible_nodes.push(node);
        node.location = { ...loc };
        // } else {
        if (node.val in old_visible_registry) {
            node.tweened_location = old_visible_registry[node.val].tweened_location;
            node.tweened_location.set(loc);
            node.tweened_size_height = old_visible_registry[node.val].tweened_size_height;
            node.tweened_size_height.set(size_height);
            node.tweened_size_width = old_visible_registry[node.val].tweened_size_width;
            node.tweened_size_width.set(size_width);
        } else {
            node.tweened_location = tweened(loc, { duration: TWEEN_DURATION, easing: TWEEN_EASING });
            node.tweened_size_height = tweened(size_height, { duration: TWEEN_DURATION, easing: TWEEN_EASING });
            node.tweened_size_width = tweened(size_width, { duration: TWEEN_DURATION, easing: TWEEN_EASING });
        }
        node.size_height = size_height;
        node.size_width = size_width;
        // TODO: use more intelligent phases
        if (node.val in old_visible_registry && keep_phases) {
            node.phase = old_visible_registry[node.val].phase;
        } else {
            node.phase = Math.random() * likelihood_model.period;
        }
        let visible_children = node.children.filter(child => child.is_visible || (keep_phases && child.val in old_visible_registry));
        let visible_children_vals = new Set(visible_children.map(child => child.val));

        if (visible_children.length > 0) {
            const numChildren = visible_children.length;
            const box_width_multiplier = 1 + BOX_WIDTH_CHILDREN_MULTIPLIER*Math.log(numChildren);
            let y_relative_bottom = 0;
            let total_children_post_Z = node.children.reduce((acc, child) => logaddexp(acc, child.post_Z), -Infinity);
            // TODO: make shrunk children have a minimum height so they don't overlap
            // TODO: we set_viztrie doesn't guarantee that retained children are valid (think about this)
            node.children.forEach((child, index) => {
                let child_frac = child.post_Z - total_children_post_Z;
                let child_height = size_height * Math.exp(child_frac);
                if (visible_children_vals.has(child.val)) {
                    // set go_live_time for new children (unless this is a likelihood_update in which case everything goes live immediately)
                    if (!(child.val in old_visible_registry)) {
                        let now = performance.now() / 1000.0;
                        console.log("WARNING: child [" + child.val + "] not in old_visible_registry, although node [" + node.val + "] is in old_visible_registry");
                        if (node.val === '' || !keep_phases) {
                            child.go_live_time = now;
                        } else if (node.go_live_time && now < node.go_live_time) {
                            // inherit go_live_time from parent if parent is not yet live
                            child.go_live_time = node.go_live_time;
                        } else {
                            // wait until parent completes the next cycle
                            let time_remaining_on_node = (node.phase - now);
                            time_remaining_on_node = time_remaining_on_node % likelihood_model.period; // map to [-period, period]
                            time_remaining_on_node = (time_remaining_on_node + likelihood_model.period) % likelihood_model.period; // map to [0, period]
                            let time_since_last_completion = likelihood_model.period - time_remaining_on_node;
                            if (time_since_last_completion < 0.250 || (node.go_live_time && now<node.go_live_time+0.250)) {
                                // allow unlimited expansion in the first 250ms after completion or going live
                                child.go_live_time = now;
                            } else {
                                let time_to_live = time_remaining_on_node + likelihood_model.mu_delay + 2.5*likelihood_model.stddev_delay;
                                let go_live_time = now + time_to_live;
                                child.go_live_time = go_live_time;
                            }
                        }
                    }
                    setLocations(child, false, {
                        x: node.location.x + node.size_width,
                        y: node.location.y + y_relative_bottom
                    }, child_height, box_width_multiplier * BOX_WIDTH);
                }
                y_relative_bottom += child_height;
            });
        }

        if (root_call) {
            old_visible_registry = {};
            visible_nodes.forEach(node => {
                old_visible_registry[node.val] = node;
            });
            if (!keep_phases) {
                keep_phases = true;
            }
        }
    }

    function draw() {
        let time = performance.now() / 1000.0;
        if (!ctx) return;
        let color;
        let color_string;
        let inverse_color;
        let inverse_color_string;

        // recalculate the time_elapsed
        if (!pause_timer) {
            time_elapsed = Math.floor((performance.now() - wpm_timer_start) / 1000);
        }
        // Calculate FPS with smoothing
        const currentTime = performance.now();
        const deltaTime = currentTime - lastFrameTime;
        const currentFps = 1000 / deltaTime;
        fps = fps * FPS_SMOOTHING + currentFps * (1 - FPS_SMOOTHING);
        fps = Math.min(100, fps);
        lastFrameTime = currentTime;

        ctx.clearRect(0, 0, canvas_element.width, canvas_element.height);
        
        let now = performance.now() / 1000.0;
        const visibleNodes = visible_nodes.filter(node => !(node.go_live_time && node.go_live_time > now));
        
        let longest_target_val_onscreen = '';
        visibleNodes.forEach(node => {
            if (target_phrase.startsWith(node.val) && node.val.length > longest_target_val_onscreen.length) {
                longest_target_val_onscreen = node.val;
            }
        });

        // Rearrange visibleNodes to put longest target match first
        visibleNodes.sort((a, b) => {
            if (a.val === longest_target_val_onscreen) return -1;
            if (b.val === longest_target_val_onscreen) return 1;
            return 0;
        });

        // Draw nodes
        visibleNodes.forEach(node => {
            color = colors.color_from_letter(node.letter);
            color_string = `rgba(${color[0]}, ${color[1]}, ${color[2]}, 0.13)`;

            ctx.beginPath();
            ctx.rect(
                get(node.tweened_location).x - get(left_offset) + 3,
                get(node.tweened_location).y + 3,
                get(node.tweened_size_width) - 6,
                get(node.tweened_size_height) - 6
            );
            ctx.strokeStyle = color_string;
            ctx.lineWidth = 2;
            if (show_boxes || developer_visualizer) {
                // ctx.stroke();
                ctx.fillStyle = color_string;
                ctx.fill();
            }
            ctx.closePath();
        });
        
        // Draw connections 
        let visible_nodes_registry = {};
        visible_nodes.forEach(node => {
            visible_nodes_registry[node.val] = node;
        });
        visibleNodes.forEach(node => {
            color = colors.color_from_letter(node.letter);
            color_string = `rgba(${color[0]}, ${color[1]}, ${color[2]}, 0.5)`;
            let darken_factor = 1.8;
            const darker_color = `rgba(${Math.floor(color[0] / darken_factor)}, ${Math.floor(color[1] / darken_factor)}, ${Math.floor(color[2] / darken_factor)}, 1.0)`;
            if (node.val.length >= 1) {
                let parent_val = node.val.slice(0, -1);
                let parent_node = visible_nodes_registry[parent_val];
                let startX = get(node.tweened_location).x + get(node.tweened_size_width) - get(left_offset) - TIMER_CIRCLE_RADIUS;
                const startY = get(node.tweened_location).y + get(node.tweened_size_height)/2;
                // move to end of circle
                startX += TIMER_CIRCLE_RADIUS;
                let endX = get(parent_node.tweened_location).x + get(parent_node.tweened_size_width) - get(left_offset) - TIMER_CIRCLE_RADIUS;
                // move to start of circle
                endX += TIMER_CIRCLE_RADIUS;
                const endY = get(parent_node.tweened_location).y + get(parent_node.tweened_size_height)/2;
                
                // Calculate control points for the curve
                const midX = (startX + endX) / 2;
                const controlPoint1X = midX;
                const controlPoint1Y = startY;
                const controlPoint2X = midX;
                const controlPoint2Y = endY;

                ctx.beginPath();
                ctx.moveTo(startX, startY);
                ctx.bezierCurveTo(
                    controlPoint1X, controlPoint1Y,
                    controlPoint2X, controlPoint2Y,
                    endX, endY
                );
                // ctx.strokeStyle = color_string;
                ctx.strokeStyle = darker_color;
                ctx.lineWidth = 2;
                ctx.stroke();
                ctx.closePath();
            }
        });

        // Draw timer circles
        visibleNodes.forEach(node => {
            const timerFrac = get_timer_frac(node, time);
            color = colors.color_from_letter(node.letter);
            color_string = `rgba(${color[0]}, ${color[1]}, ${color[2]}, 1.0)`;
            inverse_color = [255 - color[0], 255 - color[1], 255 - color[2]];
            inverse_color_string = `rgba(${inverse_color[0]}, ${inverse_color[1]}, ${inverse_color[2]}, 1.0)`;
            let timer_font_size = TIMER_FONT_SIZE;
            let timer_radius = TIMER_CIRCLE_RADIUS;
            if (use_visual_tutor && node.val === longest_target_val_onscreen) {
                timer_font_size = TIMER_FONT_SIZE * 2.0;
                timer_radius = TIMER_CIRCLE_RADIUS * 2.0;
            }
            if (node.letter === 'm' || node.letter === 'w') {
                timer_radius *= 1.15;
            }
            const centerX = get(node.tweened_location).x + get(node.tweened_size_width) - get(left_offset) - 1*TIMER_CIRCLE_RADIUS;
            const centerY = get(node.tweened_location).y + get(node.tweened_size_height)/2;
            
            // Draw circle background
            if (use_visual_tutor && node.val === longest_target_val_onscreen) {
                ctx.beginPath();
                ctx.arc(centerX, centerY, TIMER_CIRCLE_RADIUS * 3, 0, 2 * Math.PI);
                ctx.fillStyle = 'rgba(255, 255, 255, 0.2)';
                ctx.fill();
                ctx.closePath();
            }

            // Draw letter or box
            ctx.beginPath();
            // ctx.fillStyle = `rgba(${color[0]}, ${color[1]}, ${color[2]}, ${1 - Math.pow(timerFrac, 1.0)})`;
            ctx.fillStyle = color_string;
            if (node.letter === '$') {
                // Draw stop square
                const stop_square_size = 17;
                ctx.fillRect(centerX - stop_square_size/2, centerY - stop_square_size/2, stop_square_size, stop_square_size);
            } else {
                // Draw letter
                // let letter = node.letter !== ' ' ? node.letter : '_';
                ctx.font = `${timer_font_size}px verdana, helvetica, sans-serif`;
                ctx.textAlign = 'center';
                ctx.textBaseline = 'middle';
                ctx.fillText(node.letter, centerX, centerY);
            }

            // beneath in small text write bayesian info
            if (developer_visualizer) {
                ctx.font = `${timer_font_size/3}px verdana, helvetica, sans-serif`;
                ctx.fillText(`l:${node.likelihood.toFixed(2)}`, centerX, centerY + 1*timer_font_size/3);
                ctx.fillText(`p:${node.prior.toFixed(2)}`, centerX, centerY + 2*timer_font_size/3);
                ctx.fillText(`z:${node.post_Z.toFixed(2)}`, centerX, centerY + 3*timer_font_size/3);
            }
            ctx.closePath();


            // ctx.globalCompositeOperation = 'xor';
            // Draw timer arc
            ctx.beginPath();
            ctx.arc(centerX, centerY, timer_radius, 0, 2 * Math.PI * timerFrac);
            // ctx.strokeStyle = color_string;
            // ctx.strokeStyle = inverse_color_string;
            // ctx.strokeStyle = 'white';
            // ctx.strokeStyle = `rgba(255, 255, 255, ${timerFrac*0.9+0.1})`;
            if (TIMER_COLOR === 'color') {
                ctx.strokeStyle = `rgba(${color[0]}, ${color[1]}, ${color[2]}, ${timerFrac*0.9+0.1})`;
            } else if (TIMER_COLOR === 'white') {
                ctx.strokeStyle = `rgba(255, 255, 255, ${timerFrac*0.9+0.1})`;
            } else {
                throw new Error("Invalid TIMER_COLOR: " + TIMER_COLOR);
            }
            ctx.lineWidth = TIMER_CIRCLE_WIDTH;
            if (use_visual_tutor && node.val === longest_target_val_onscreen) {
                ctx.lineWidth = TIMER_CIRCLE_WIDTH * 2;
            }
            ctx.stroke();
            ctx.closePath();
            // ctx.globalCompositeOperation = 'source-over';
        });


        animationFrameId = requestAnimationFrame(draw);
    }

</script>

<div class="flex flex-col h-full relative box-border">
    <canvas bind:this={canvas_element} class="h-full w-full bg-black"></canvas>
    <div class="absolute top-4 right-6 flex gap-8 text-white text-2xl">
        <label class="flex items-center gap-3">
            <input type="checkbox" bind:checked={blink_to_click} class="w-6 h-6"/>
            Blink to click
        </label>
        <label class="flex items-center gap-3">
            <input type="checkbox" bind:checked={developer_visualizer} class="w-6 h-6"/>
            Debug
        </label>
        <label class="flex items-center gap-3">
            <input type="checkbox" bind:checked={play_click_sound} class="w-6 h-6"/>
            Click sound
        </label>
        <label class="flex items-center gap-3">
            <input type="checkbox" bind:checked={show_boxes} class="w-6 h-6"/>
            Boxes
        </label>
        <label class="flex items-center gap-3">
            <input type="checkbox" bind:checked={use_visual_tutor} class="w-6 h-6"/>
            Tutor
        </label>
        <label class="flex items-center gap-3">
            <input type="checkbox" bind:checked={multiline_mode} class="w-6 h-6"/>
            Multiline
        </label>
    </div>
</div>

{#if blink_to_click}
    <Eye on:blink={click}/>
{/if}
